<?php

declare(strict_types=1);

/**
 * Rector config for the PHPUnit -> Testo migration (set: phpunit-to-testo).
 *
 * Generated by the testo-migrate-from-phpunit skill. This file is disposable: once the
 * migration is verified under `vendor/bin/testo`, delete it (and the bridge from
 * require-dev if you no longer need it).
 *
 * The set performs the MECHANICAL conversions only (assert calls + arg-order, lifecycle
 * methods -> attributes, data providers, groups, #[CoversClass] -> #[Covers], bare
 * expectException, markTestSkipped). It does NOT remove `extends TestCase`, reconcile test
 * discovery, or convert mocks -- finish those with an AI/human pass (see the skill).
 *
 * Dry-run:  vendor/bin/rector process --config=rector-testo-migration.php --dry-run
 * Apply:    vendor/bin/rector process --config=rector-testo-migration.php
 */

use Rector\Config\RectorConfig;
use Testo\Bridge\Rector\Set\TestoRectorSetList;

return RectorConfig::configure()
    ->withPaths([
        __DIR__ . '/tests',
    ])
    ->withSets([
        TestoRectorSetList::PHPUNIT_TO_TESTO,
    ]);
