---

on:  # yamllint disable-line rule:truthy
  pull_request:
    paths:
      - 'src/**'
      - 'bin/dload'
      - '.php-cs-fixer.dist.php'
      - 'psalm*'
      - 'composer.*'
  push:
    paths:
      - 'src/**'
      - 'bin/dload'
      - '.php-cs-fixer.dist.php'
      - 'psalm*'
      - 'composer.*'

name: 🔍 Static analysis

jobs:
  psalm:
    timeout-minutes: 4
    runs-on: ${{ matrix.os }}
    concurrency:
      cancel-in-progress: true
      group: psalm-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
        php-version:
          - '8.2'
        dependencies:
          - locked
    steps:
      - name: 📦 Check out the codebase
        uses: actions/checkout@v4

      - name: 🛠️ Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          ini-values: error_reporting=E_ALL
          coverage: none

      - name: 🛠️ Setup problem matchers
        run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"

      - name: 🤖 Validate composer.json and composer.lock
        run: composer validate --ansi --strict

      - name: 📥 Install dependencies with composer
        uses: ramsey/composer-install@v3
        with:
          dependency-versions: ${{ matrix.dependencies }}

      - name: 🔍 Run static analysis using vimeo/psalm
        run: composer psalm:ci
